### ISSUE TITLE
Varnish failed to start because unable to resolve hostname web

### ISSUE THREAD

**Issue by frostblogNet** [drud/ddev-varnish#1]
﻿ddev v1.19.1

Error:
Message from VCC-compiler:
Backend host '"web"' could not be resolved to an IP address:
        Name or service not known
(Sorry if that error message is gibberish.)
('/etc/varnish/default.vcl' Line 8 Pos 11)
  .host = "web";
----------#####-`

Do you have any idea how to solve this.

Thanks

**Comment by rfay** [comment]
Thanks @frostblogNet - Could you try 
* #2 
You can just add 
```
depends_on:
- web
```

**Comment by cmuench** [comment]
> Thanks @frostblogNet - Could you try
> 
> * [Make varnish not come up until web container is up, fixes #1 #2](https://github.com/drud/ddev-varnish/pull/2)
>   You can just add
> 
> ```
> depends_on:
> - web
> ```

Tested the Magento shop. Works on my machine with Varnish 6 and `depends_on` setting.

**Comment by cmuench** [comment]
@rfay For M1 Mac I had to add `platform: linux/x86_64`, because there is no arm/v8 image available.

**Comment by cmuench** [comment]
> @rfay For M1 Mac I had to add `platform: linux/x86_64`, because there is no arm/v8 image available.

Found a arm/v8 image -> v6.6

**Comment by rfay** [comment]
6.0 is "stable" == 6.0.10 I think, and it has arm64, https://hub.docker.com/_/varnish?tab=tags&page=1&name=6.0

**Comment by rfay** [comment]
Followup for 6.0, 
* https://github.com/drud/ddev-varnish/pull/3

**Comment by frostblogNet** [comment]
Hello @rfay 

Thanks depends on works for us. There is still a problem with additional_fqdns but I have to invastigate to find out what is the root cause of this issue.

**Comment by rfay** [comment]
I'm not completely sure additional_fqdns has every worked with varnish... Did it work for you before? The problem is that ddev-router manages that and varnish injects itself in front.

**Comment by rfay** [comment]
Please open an issue or PR about additional_fqdns/additional_hostnames so it can be documented if that's the case.
