### ISSUE TITLE
ddev launch -m shortcut for mailhog doesn't work when ddev/varnish enabled

### ISSUE THREAD

**Issue by jedubois** [drud/ddev-varnish#10]
For projects which use mailhog the ddev-varnish add-on causes `ddev launch -m` to stop working since mailhog is no longer available on the expected URL. The launch command isn't the important but it's pretty neat.

*Workaround*: Access mailhog on novarnish.* URL. 

*Discussion*: Off the top of my head, without knowing all that much about internals, 3 options: a) document as gotcha in README; b) have router handle port 8026 differently; c) handle port 8026 on varnish container, e.g. have Varnish listen on that port too and just pass requests along to web container on same port, or direct to novarish.* URL, or use something like socat to relay the traffic. 

### STEPS TO REPRODUCE:

**Outline**

1. Create a very simple ddev project.
2. Start ddev
3. Launch mailhog: there it is!
4. Add ddev-varnish
5. Restart ddev 
6. Launch mailhog: '503: No ddev back-end site available.'

**Worked example with output**

$ ddev version
 ITEM             VALUE
 DDEV version     v1.21.3
 architecture     amd64
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.3
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.3
 docker           20.10.20
 docker-compose   v2.10.2
 docker-platform  docker-desktop
 mutagen          0.16.0
 os               darwin
 router           drud/ddev-router:v1.21.3
 web              drud/ddev-webserver:v1.21.3

$ ddev poweroff
$ mkdir /tmp/testddev
$ cd /tmp/testddev
$ ddev config --auto
$ printf "<?php\nphpinfo();\n" > index.php
$ ddev start
...
Successfully started testddev
Project can be reached at https://testddev.ddev.site https://127.0.0.1:62323

$ ddev launch -m 

Opens Mailhog at https://testddev.ddev.site:8026 with system default browser.

$ ddev get drud/ddev-varnish && ddev restart
$ ddev restart

$ ddev launch -m 

Still opens https://testddev.ddev.site:8026 with system default browser but now it's an error page from the router container: "502: Unresponsive/broken ddev back-end site."

**Comment by rfay** [comment]
It's super easy to add a launch command in this add-on that will do this correctly. Just copy the [normal one](https://github.com/drud/ddev/blob/master/pkg/ddevapp/global_dotddev_assets/commands/host/launch) and put it in this add-on (installed to .ddev/commands/host) and update it to work with varnish.

**Comment by rfay** [comment]
BTW, you use this a lot, I'd love to see you become a maintainer of it. Would you consider that @jedubois ?

**Comment by jedubois** [comment]
@rfay , I would be happy to help but not don't feel super confident after going down a rabbit hole with Go today 🙈

**Comment by rfay** [comment]
Mostly this isn't related to go, but more related to your experience with varnish, and I'm way happy to help with anything that is go related. The most important thing is to have somebody watching that uses varnish regularly (which isn't me).

**Comment by jedubois** [comment]
@skeemer , thanks for this fix. I did some testing, merged your PR, did release, merged your test PR. Using v0.1.3 on my projects now.

**Comment by rfay** [comment]
Thanks @jedubois !
