### ISSUE TITLE
Router config error when additional_hostnames set

### ISSUE THREAD

**Issue by jedubois** [drud/ddev-varnish#4]
For projects with additional_hostnames set the ddev-varnish configuration causes configuration errors for nginx in the ddev-router service. $DDEV_HOSTNAME is a comma separated list of hostnames. However, when ddev-varnish switches the name of the VIRTUAL_HOST for the web service only the first hostname in the list gets "novarnish." prepended. This leads to router's nginx config having duplicate upstreams for the 2nd hostname and higher.

DDEV_HOSTNAME=testddev.ddev.site,testadd.ddev.site
Environment variable passed to web: VIRTUAL_HOST=novarnish.testddev.ddev.site,testadd.ddev.site 

I'm not familiar enough with DDEV to see how one could hook in and create a new environment variable, e.g. $DDEV_VARNISH_NOVARNISH, which contains a comma separated list of hostnames with "novarnish.*" prepended. 

**Workaround** Modify docker-compose.varnish.yaml and set VIRTUAL_HOST manually:
VIRTUAL_HOST=novarnish.testddev.ddev.site,novarnish.testadd.ddev.site

### STEPS TO REPRODUCE:

**Outline**
1) Create a very simple ddev project.
2) Modify config.yml with additional_hostnames.
3) Start ddev and all is well: project available on all hostnames.
4) Add ddev-varnish
5) Restart ddev and router doesn't become healthy: project not available at hostnames.
6) Check logs to see errors from Varnish.

**Worked example with output**
$ ddev version
 ITEM             VALUE
 DDEV version     v1.19.2
 architecture     amd64
 db               drud/ddev-dbserver-mariadb-10.3:v1.19.2
 dba              phpmyadmin:5
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.19.0
 docker           20.10.14
 docker-compose   v2.3.3
 docker-platform  docker-desktop
 mutagen          0.12.0
 os               darwin
 router           drud/ddev-router:v1.19.0
 web              drud/ddev-webserver:v1.19.2

$ ddev poweroff
$ mkdir ~/tmp/testddev
$ cd ~/tmp/testddev
$ ddev config --auto
$printf "<?php\nphpinfo();\n" > index.php
$ ddev start
… 
Successfully started testddev
Project can be reached at https://testddev.ddev.site/ https://127.0.0.1:64495/

Edit config.yml to add an additional_hostname:
additional_hostnames:
  - testadd

$ ddev restart
…
Restarted testddev
Your project can be reached at https://testddev.ddev.site/ https://testadd.ddev.site/ https://127.0.0.1:64509/

$ ddev get drud/ddev-varnish

$ ddev restart
…
Container ddev-router  Started
Failed to restart testddev: ddev-router failed to become ready; debug with 'docker logs ddev-router'; logOutput=, err=health check timed out: labels map[com.docker.compose.service:ddev-router] timed out without becoming healthy, status=

$ docker inspect --format "{{json .State.Health }}" ddev-router
{"Status":"starting","FailingStreak":87,"Log":[{"Start":"2022-05-25T10:37:31.680100162Z","End":"2022-05-25T10:37:31.777792309Z","ExitCode":2,"Output":"nginx configuration invalid: 2022/05/25 10:37:31 [emerg] 3147#3147: duplicate upstream \"testadd.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:181\nnginx: [emerg] duplicate upstream \"testadd.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:181\nnginx: configuration file /etc/nginx/nginx.conf test failed"},{"Start":"2022-05-25T10:37:32.784184621Z","End":"2022-05-25T10:37:32.879123543Z","ExitCode":2,"Output":"nginx configuration invalid: 2022/05/25 10:37:32 [emerg] 3158#3158: duplicate upstream \"testadd.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:181\nnginx: [emerg] duplicate upstream \"testadd.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:181\nnginx: configuration file /etc/nginx/nginx.conf test failed"},{"Start":"2022-05-25T10:37:33.886245395Z","End":"2022-05-25T10:37:33.994267865Z","ExitCode":2,"Output":"nginx configuration invalid: 2022/05/25 10:37:33 [emerg] 3169#3169: duplicate upstream \"testadd.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:181\nnginx: [emerg] duplicate upstream \"testadd.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:181\nnginx: configuration file /etc/nginx/nginx.conf test failed"},{"Start":"2022-05-25T10:37:35.001539476Z","End":"2022-05-25T10:37:35.113039053Z","ExitCode":2,"Output":"nginx configuration invalid: 2022/05/25 10:37:35 [emerg] 3181#3181: duplicate upstream \"testadd.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:181\nnginx: [emerg] duplicate upstream \"testadd.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:181\nnginx: configuration file /etc/nginx/nginx.conf test failed"},{"Start":"2022-05-25T10:37:36.118069465Z","End":"2022-05-25T10:37:36.218200491Z","ExitCode":2,"Output":"nginx configuration invalid: 2022/05/25 10:37:36 [emerg] 3192#3192: duplicate upstream \"testadd.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:181\nnginx: [emerg] duplicate upstream \"testadd.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:181\nnginx: configuration file /etc/nginx/nginx.conf test failed"}]}

**Comment by rfay** [comment]
Yes, the "put varnish in front" thing here is very naive. I'll see if there's an obvious way to make it more robust.

**Comment by rfay** [comment]
It seems the problem here is that ddev-router is creating two nginx upstreams for the second hostname. 

For example, I added `additional_hostnames: [one]` and now I see

```json
        upstream one.ddev.site-80 {
        keepalive 100;
            # Container=ddev-d9-varnish 172.21.0.6:80
            server ddev-d9-varnish:80;
        }
        upstream one.ddev.site-80 {
        keepalive 100;
            # Container=ddev-d9-web 172.21.0.5:80
            server ddev-d9-web:80;
        }
```

It's creating one upstream pointing to ddev-d9-varnish (correct) and another pointing to ddev-d9-web (incorrect)

So this is probably just an error in the complex ddev-router script that tries to sort out VIRTUAL_HOST.

VIRTUAL_HOST *is* supposed to handle multiple comma-separated hostnames ... Just doesn't seem to work out here.

**Comment by plach79** [comment]
I'm getting exactly the same issue reported above by @jedubois (thanks for sharing the workaround!)

```
$ ddev start
Network ddev_default created 
Starting ddev-test... 
Container ddev-ssh-agent  Started 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Pushed mkcert rootca certs to ddev-global-cache/mkcert 
Network ddev-ddev-test_default  Created 
Container ddev-ddev-test-dba  Started 
Container ddev-ddev-test-db  Started 
Container ddev-ddev-test-db  Healthy 
Container ddev-ddev-test-web  Started 
Container ddev-ddev-test-varnish  Started 
Container ddev-router  Started 
Failed to start ddev-test: ddev-router failed to become ready; debug with 'docker logs ddev-router'; logOutput=, err=health check timed out: labels map[com.docker.compose.service:ddev-router] timed out without becoming healthy, status= 
$ docker inspect --format "{{json .State.Health }}" ddev-router
{"Status":"starting","FailingStreak":0,"Log":[{"Start":"2022-08-06T09:20:14.13745446Z","End":"2022-08-06T09:20:14.210430501Z","ExitCode":2,"Output":"nginx configuration invalid: 2022/08/06 09:20:14 [emerg] 1626#1626: duplicate upstream \"ddev-test-alt.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:79\nnginx: [emerg] duplicate upstream \"ddev-test-alt.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:79\nnginx: configuration file /etc/nginx/nginx.conf test failed"},{"Start":"2022-08-06T09:20:15.214098176Z","End":"2022-08-06T09:20:15.286723008Z","ExitCode":2,"Output":"nginx configuration invalid: 2022/08/06 09:20:15 [emerg] 1636#1636: duplicate upstream \"ddev-test-alt.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:79\nnginx: [emerg] duplicate upstream \"ddev-test-alt.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:79\nnginx: configuration file /etc/nginx/nginx.conf test failed"},{"Start":"2022-08-06T09:20:16.290308521Z","End":"2022-08-06T09:20:16.363159004Z","ExitCode":2,"Output":"nginx configuration invalid: 2022/08/06 09:20:16 [emerg] 1646#1646: duplicate upstream \"ddev-test-alt.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:79\nnginx: [emerg] duplicate upstream \"ddev-test-alt.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:79\nnginx: configuration file /etc/nginx/nginx.conf test failed"},{"Start":"2022-08-06T09:20:17.366826002Z","End":"2022-08-06T09:20:17.436363039Z","ExitCode":2,"Output":"nginx configuration invalid: 2022/08/06 09:20:17 [emerg] 1656#1656: duplicate upstream \"ddev-test-alt.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:79\nnginx: [emerg] duplicate upstream \"ddev-test-alt.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:79\nnginx: configuration file /etc/nginx/nginx.conf test failed"},{"Start":"2022-08-06T09:20:18.440790519Z","End":"2022-08-06T09:20:18.514996439Z","ExitCode":2,"Output":"nginx configuration invalid: 2022/08/06 09:20:18 [emerg] 1666#1666: duplicate upstream \"ddev-test-alt.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:79\nnginx: [emerg] duplicate upstream \"ddev-test-alt.ddev.site-80\" in /etc/nginx/conf.d/ddev.conf:79\nnginx: configuration file /etc/nginx/nginx.conf test failed"}]}
```

with the the following `config.yml`:

```yml
name: ddev-test
type: php
docroot: web
php_version: "8.0"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: [
  'ddev-test-alt',
  'ddev-test-alt2',
]
additional_fqdns: []
database:
  type: mariadb
  version: "10.4"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "16"
```

**Comment by plach79** [comment]
Additionally, I found that adding the `project_tld` setting (after commenting out additional hostnames) prevents direct access to the web service:

```
$ ddev restart
Restarting project ddev-test... 
Container ddev-ddev-test-dba  Removed 
Container ddev-ddev-test-varnish  Removed 
Container ddev-ddev-test-web  Removed 
Container ddev-ddev-test-db  Removed 
Network ddev-ddev-test_default  Removed 
Pushed mkcert rootca certs to ddev-global-cache/mkcert 
Network ddev-ddev-test_default  Created 
Container ddev-ddev-test-dba  Started 
Container ddev-ddev-test-db  Started 
Container ddev-ddev-test-db  Healthy 
Container ddev-ddev-test-web  Started 
Container ddev-ddev-test-varnish  Started 
Container ddev-router  Started 
Restarted ddev-test 
Your project can be reached at https://ddev-test.drupal.org https://127.0.0.1:51364 

$ curl -D headers.log https://ddev-test.drupal.org/ > /dev/null 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  115k  100  115k    0     0  3725k      0 --:--:-- --:--:-- --:--:-- 3725k
$ cat headers.log 
HTTP/2 200 
server: nginx/1.20.1
date: Sat, 06 Aug 2022 09:23:49 GMT
content-type: text/html; charset=UTF-8
content-length: 118261
vary: Accept-Encoding
x-varnish: 5 32774
age: 118
via: 1.1 varnish (Varnish/6.0)
accept-ranges: bytes

$ curl -D headers.log https://novarnish.ddev-test.drupal.org/ > /dev/null 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL: no alternative certificate subject name matches target host name 'novarnish.ddev-test.drupal.org'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
$ curl -D headers.log https://novarnish.ddev-test.ddev.site/ > /dev/null 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL: no alternative certificate subject name matches target host name 'novarnish.ddev-test.ddev.site'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

with `config.yml`:

```
name: ddev-test
type: php
docroot: web
php_version: "8.0"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: [
#  'ddev-test-alt',
#  'ddev-test-alt2',
]
additional_fqdns: []
project_tld: drupal.org  # <----
  type: mariadb
  version: "10.4"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "16"
```

**Comment by plach79** [comment]
Ideally, I would expect every additional hostname to be accessible via Varnish and the configured `novarnish` prefix to be available for every one of them as well, e.g.:

* `ddev-test.drupal.org` → proxied by Varnish
* `novarnish.ddev-test.drupal.org` → direct access to the web service
* `ddev-test-alt.drupal.org` → proxied by Varnish
* `novarnish.ddev-test-alt.drupal.org` → direct access to the web service
* `ddev-test-alt2.drupal.org` → proxied by Varnish
* `novarnish.ddev-test-alt2.drupal.org` → direct access to the web service

**Comment by plach79** [comment]
I was able to fully work around the issues above this way:

* In `docker-compose.varnish.yaml` I applied the following changes:
```diff
--- docker-compose.varnish.original.yaml	2022-08-06 14:05:08.000000000 +0200
+++ docker-compose.varnish.yaml	2022-08-06 14:00:02.000000000 +0200
@@ -30,4 +30,5 @@
   # container, just by switching the names.
   web:
     environment:
-      - VIRTUAL_HOST=novarnish.$DDEV_HOSTNAME
+      - VIRTUAL_HOST=novarnish.ddev-test.drupal.org,novarnish.ddev-test-alt.drupal.org,novarnish.ddev-test-alt2.drupal.org
+      - DDEV_HOSTNAME=novarnish.ddev-test.drupal.org,novarnish.ddev-test-alt.drupal.org,novarnish.ddev-test-alt2.drupal.org
```
* Then I manually added the hostnames:
```
sudo ddev hostname novarnish.ddev-test.drupal.org 127.0.0.1;
sudo ddev hostname novarnish.ddev-test-alt.drupal.org 127.0.0.1;
sudo ddev hostname novarnish.ddev-test-alt2.drupal.org 127.0.0.1;
```

Ugly but it works :)

**Comment by rfay** [comment]
Awesome!

**Comment by rfay** [comment]
@jedubois @plach79 I think #9 will probably work for you, and I'd love it if you'd try it out. Instructions are in the PR, but it's just
```
ddev get https://github.com/rfay/ddev-varnish/tarball/20221029_varnish_multiple_hostnames
```

**Comment by jedubois** [comment]
@rfay , thanks for giving this issue some love. I did a quick test of #9 in an existing project; however, it seems to be treating  additional-hostnames the same as additional_fqdns so the entries for my additional hostnames in .ddev/docker-compose.varnish-extras.yaml are not having ddev.site appended.

In other words for additional-hostnames I expect 'testadd' to generate 'novarnish.testadd.ddev.site' while for additional_fqdns I expect 'testadd.mydomain.com' to generate 'novarnish.testadd.mydomain.com'.

**Comment by rfay** [comment]
What is the explicit need for novarnish.testadd.ddev.site? (I did notice that it generates `novarnish.testadd` instead... but it's mostly a throwaway. I found that everything was working with the varnish version though.

It's hard for the add-on to know for sure what the tld is, but I guess it can look in both project and global config for that.

**Comment by jedubois** [comment]
It's about being consistent with the DDEV docs/behaviour which differentiate between additional_hostnames and additional_fqdns and of course when we use *.ddev.site it's not necessary to add local hosts entries. 

For my personal use it's not a big deal but I put the environments together for other team members to use too and inconsistency/confusion/many people needing to consistently do the same manual steps is always an issue.

**Comment by rfay** [comment]
I'm asking why the additional steps... do you use the `novarnish` hostnames for something? But I will add the tld to the novarnish.

**Comment by jedubois** [comment]
Yes, the main project is a complicated multi-domain, using Domain (https://www.drupal.org/project/domain), where it's quite useful to be able to bypass Varnish for some frontend and testing stuff while still having Varnish locally for more 'realistic' impression of how things work for the normal user. 

Right now we have Domain configured to expect virtual hosts to be full names, e.g. addhost.ddev.site & novarnish.addhost.ddev.site. I like doing it that way rather than say configuring it to look for just 'addhost' because it's consistent with what the user is seeing in their browser and how it's done in DEV/STAGE/PROD hosted environments. 

**Using the steps in original post with the new code, two additional hostnames and one additional FQDN this is what gets through to the web server (as per phpinfo()).**

config.yml:
```
name: testddev
type: php
...
additional_hostnames:
- testaddhost
- testaddhost1
additional_fqdns:
- testaddfqdn.random.tld
```

Vanilla DDEV:
> DDEV_TLD 	ddev.site 
> DDEV_HOSTNAME testddev.ddev.site,testaddfqdn.random.tld,testaddhost.ddev.site,testaddhost1.ddev.site 
> DDEV_PROJECT 	testddev 
> VIRTUAL_HOST 	testddev.ddev.site,testaddfqdn.random.tld,testaddhost.ddev.site,testaddhost1.ddev.site

DDEV with Varnish #9:
> DDEV_TLD 	ddev.site 
> DDEV_HOSTNAME 	testddev.ddev.site,testaddfqdn.random.tld,testaddhost.ddev.site,testaddhost1.ddev.site 
> DDEV_PROJECT 	testddev 
> VIRTUAL_HOST 	novarnish.testaddhost,novarnish.testaddhost1,novarnish.testaddfqdn.random.tld,novarnish.testddev

**Comment by rfay** [comment]
Thanks!

**Comment by rfay** [comment]
Please take another look at https://github.com/drud/ddev-varnish/pull/9#issuecomment-1295906703 and see if it meets your needs now, thanks!

**Comment by jedubois** [comment]
Success. I've tested it on the simple case and on an actual project and both work perfectly. 

Tomorrow I'll see about updating the README to remind users of two things:

1. If they use a non-default project_tld or additional_fqdns DDEV will help them add hosts entries for the 'normal' hostnames automagically; however, they'll need to add them for  novarnish.* sub-domains themselves, e.g. `ddev hostname novarnish.testaddfqdn.random.tld 127.0.0.1`
2. They need to run `ddev get drud/ddev-varnish` after any updates to project which update hostnames/fqdn, e.g. adding another additional_hostname, so that .ddev/docker-compose.varnish-extras.yaml is updated.

**Comment by rfay** [comment]
Fantastic. Why don't you go ahead and pull this when you're ready. Then please create a release (Release version isn't very important). But the plain `ddev get` gets latest release.

**Comment by rfay** [comment]
This could probably add the novarnish hostnames. Maybe we can save that as an exercise for later PR.

**Comment by jedubois** [comment]
> Fantastic. Why don't you go ahead and pull this when you're ready. Then please create a release (Release version isn't very important). But the plain `ddev get` gets latest release.

I've created release v0.1.2 and published it. Adjusted the tests to check that the novarnish.* variants exist too. Will do a PR for re-enabling the install from release tests in due course.

> This could probably add the novarnish hostnames. Maybe we can save that as an exercise for later PR.

Keep it on this ticket or create a new one? Give me a on how to do this/where to find examples and I'll give it a go.
